server:
  port: 8099

spring:
  profiles:
    # todo 验证先后关系的生效优先级
    include: config
    active: dev

# DataSource Config
  datasource:
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&rewriteBatchedStatements=TRUE
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Ashe1235
