server:
  port: 8099

spring:
  profiles:
    # todo 验证先后关系的生效优先级
    include: config
    active: dev

# DataSource Config
  datasource:
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&rewriteBatchedStatements=TRUE
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Ashe1235

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: isDeleted  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
